name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Assert version
        run: |
          set -eux
          test refs/tags/v`python ./setup.py --version` == "${{ github.ref }}"
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-python3.8-${{ hashFiles('**/Pipfile.lock') }}-pipcache
      - name: Cache environment
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python3.8-${{ hashFiles('**/Pipfile.lock') }}-venv
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: |
          set -eux
          if ! pipenv run twine --version
          then
              make publish-installdeps
          fi
          pipenv run twine --version
      - name: Publish to pypi
        run: make publish publish_repository=pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Molecule does not work on Python3.5
        python-version: [3.8]
        remote-python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        # Molecule requires ansible >= 2.8
        ansible-version: [2.8.10, 2.9.6]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache packages
        # https://github.com/actions/cache/issues/152
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-python${{ matrix.python-version }}-ansible${{ matrix.ansible-version }}-pipcache }}
      - name: Cache environment
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python${{ matrix.python-version }}-ansible${{ matrix.ansible-version }}-venv }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: |
          set -eux
          # Do not use pipenv install to specify ansible version here
          # (Locking is very slow and is it not needed)
          pipenv run python -m pip install ansible==${{ matrix.ansible-version }}
          pipenv run python -m pip install .[dev]
          # Check versions
          pipenv run ansible --version
          pipenv run molecule --version
      - name: Run test
        run: make test remote_python_version=${{ matrix.remote-python-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-python3.8-${{ hashFiles('**/Pipfile.lock') }}-pipcache
      - name: Cache environment
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python3.8-${{ hashFiles('**/Pipfile.lock') }}-venv
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: |
          set -eux
          make installdeps
      - name: Run linter
        run: make lint
