name: Test CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: make installdeps
      - name: Run molecule test
        run: make check
