name: Test CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: make installdeps
      - name: Run molecule test
        run: pipenv
