name: Test CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache dependencies
        # https://github.com/actions/cache/issues/152
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup Python3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        run: python -m pip install pipenv
      - name: Install denendencies
        run: make installdeps && pipenv run which molecule
      - name: Run molecule test
        run: make check
